- name: Hardening Server Setup
  hosts: all
  become: true
  vars:
    ssh_port: 22

  tasks:
    - name: Create a new user with sudo privileges
      user:
        name: '{{ target_user }}'
        shell: /bin/bash
        groups: sudo
        append: yes
        state: present
      when: target_user != ""

    - name: Set password user
      user:
        name: '{{ target_user }}'
        password: '{{ target_user_password_hash }}'
      when: target_user_password_hash != ""


    - name: Set up authorized keys (SSH)
      authorized_key:
        user: '{{ target_user }}'
        state: present
        key: '{{ user_ssh_public_key }}'
      when: target_user != ""

    - name: Configure SSH Daemon
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '{{ item.regexp }}'
        line: '{{ item.line }}'
        state: present
        validate: 'sshd -t -f %s'
      loop:
        - { regexp: '^PermitRootLogin', line: 'PermitRootLogin no' }
        - { regexp: '^PermitEmptyPasswords', line: 'PermitEmptyPasswords no' }
        - {
            regexp: '^PasswordAuthentication',
            line: 'PasswordAuthentication no',
          }
      notify: Restart SSH

    - name: Install Fail2Ban
      apt:
        name: fail2ban
        state: present
        update_cache: no
      when: ansible_os_family == "Debian"

    - name: Configure Fail2Ban local config
      copy:
        dest: /etc/fail2ban/jail.local
        content: |
          [DEFAULT]
          bantime  = 1h
          findtime = 10m
          maxretry = 3

          [sshd]
          enabled = true
          port    = {{ ssh_port }}
      notify: Restart Fail2Ban

    - name: Install UFW
      apt:
        name: ufw
        state: present
      when: ansible_os_family == "Debian"

    - name: Reset UFW to default (incoming deny, outgoing allow)
      ufw:
        direction: '{{ item.direction }}'
        policy: '{{ item.policy }}'
      loop:
        - { direction: 'incoming', policy: 'deny' }
        - { direction: 'outgoing', policy: 'allow' }

    - name: Allow SSH connection
      ufw:
        rule: allow
        port: '{{ ssh_port | string }}'
        proto: tcp

    - name: Allow defined ports
      ufw:
        rule: allow
        port: '{{ item | string }}'
        proto: tcp
      loop: '{{ allow_ports }}'

    - name: Enable UFW
      ufw:
        state: enabled

    - name: Disable ICMP echo requests (Ping) at kernel level
      ansible.posix.sysctl:
        name: net.ipv4.icmp_echo_ignore_all
        value: '1'
        state: present
        reload: yes

    - name: Disable ICMP broadcasts (protection against Smurf attacks)
      ansible.posix.sysctl:
        name: net.ipv4.icmp_echo_ignore_broadcasts
        value: '1'
        state: present
        reload: yes

  handlers:
    - name: Restart SSH
      service: name=ssh state=restarted
    - name: Restart Fail2Ban
      service: name=fail2ban state=restarted
